#big ol file of character traits
interests = [
    "Sports",
    "Music",
    "Arts and crafts",
    "Reading",
    "Gaming",
    "Cooking and baking",
    "Traveling",
    "Photography",
    "Gardening",
    "Fitness and exercise",
    "Writing",
    "Technology",
    "Nature and outdoor activities",
    "Film and cinema",
    "Fashion and style",
    "Volunteering and activism",
    "Pets and animals",
    "History and archaeology",
    "DIY projects",
    "Meditation and mindfulness",
    "Dancing",
    "Drawing",
    "Singing",
    "Board games",
    "Playing instruments",
    "Knitting and crocheting",
    "Poetry",
    "Video games",
    "Experimenting with recipes",
    "Exploring new cultures",
    "Landscape photography",
    "Growing flowers",
    "Running",
    "Novels",
    "Programming",
    "Hiking",
    "Watching movies",
    "Following fashion trends",
    "Environmental causes",
    "Caring for pets",
    "Studying ancient civilizations",
    "Home improvement",
    "Yoga",
    "Analyzing cinematography",
    "Personal styling",
    "Social justice",
    "Wildlife conservation",
    "Historical events",
    "Furniture restoration",
    "Spiritual growth",
    "Acting",
    "Painting",
    "Composing music",
    "Role-playing games",
    "Cake decorating",
    "Visiting historical sites",
    "Birdwatching",
    "Short stories",
    "Building computers",
    "Camping",
    "Documentary films",
    "Following food blogs",
    "Learning new languages",
    "Robotics",
    "Birdwatching",
    "Blogging",
    "Marine biology",
    "Vintage fashion",
    "Humanitarian work",
    "Scuba diving",
    "Sketching",
    "Group fitness classes",
    "Science fiction",
    "Interior design",
    "Stargazing",
    "Collecting antiques",
    "Journaling",
    "Coding challenges",
    "Mountain biking",
    "Graphic design",
    "Martial arts",
    "Pottery",
    "Metal detecting",
    "Online courses",
    "Urban exploration",
    "Vintage cars",
    "Animation",
    "Stand-up comedy",
    "Fine dining",
    "Amateur radio",
    "Cocktail making",
    "Cognitive psychology",
    "Thrill-seeking activities",
    "Astrology",
    "Photography editing",
    "Antique restoration",
    "Beekeeping",
    "Fashion design",
    "Cryptocurrency trading",
    "Ghost hunting",
    "Skiing and snowboarding",
    "Cultural anthropology",
    "Beekeeping",
    "Political activism",
    "App development",
    "Cosplay",
    "Collecting vinyl records",
    "Basket weaving",
    "Astrophotography",
    "Genealogy",
    "Woodworking",
    "Studying mythology",
    "Foraging",
    "Tattoo artistry",
    "Horseback riding",
    "Graffiti art",
    "Social media management",
    "Ice skating",
    "Model building",
    "Belly dancing",
    "Wine tasting",
    "Basketball",
    "Paragliding",
    "Ghostwriting",
    "Paddleboarding",
    "Pilates",
    "Quilting",
    "Model railroading",
    "Kite flying",
    "Caving",
    "Urban gardening",
    "Whale watching",
    "Competitive eating",
    "Remote control hobbies",
    "Parkour",
    "Drone flying",
    "Astrology",
    "Bungee jumping",
    "Esports",
    "Biographies",
    "Soap making",
    "Stand-up paddleboarding",
    "Live music events",
    "Butterfly watching",
    "Chess",
    "Spelunking",
    "Collecting coins",
    "Geocaching",
    "Seashell collecting",
    "Competitive baking",
    "Collecting stamps",
    "Scrapbooking",
    "Hula hooping",
    "Jigsaw puzzles",
    "Origami",
    "Skydiving",
    "Circus arts",
    "Scavenger hunts",
    "Sandcastle building",
    "Hot air ballooning",
    "Videography",
    "Aquarium keeping",
    "Competitive gardening",
    "Street art",
    "Herbalism",
    "Aquascaping",
    "Capoeira",
    "Ceramics",
    "Taxidermy",
    "Card magic",
    "Fire dancing",
    "Watercolor painting",
    "Yachting",
    "Beekeeping",
    "Hiking",
    "Geocaching",
    "Lego building",
    "Butterfly gardening",
    "Archery",
    "Metalworking",
    "Falconry",
    "Dowsing",
    "Extreme ironing",
    "Orienteering",
    "Lawn darts",
    "Kite fighting",
    "Ultimate frisbee",
    "Sandboarding",
    "Skijoring",
    "Sled dog racing",
    "Underwater hockey",
    "Yukigassen",
    "Zorbing",
    "Backpacking",
    "Base jumping",
    "Freestyle skiing",
    "Bobsleighing",
    "Canyoneering",
    "Cave diving",
    "Cheerleading",
    "Cross-country skiing",
    "Dog sledding",
    "Freediving",
    "Freerunning",
    "Hang gliding",
    "Highlining",
    "Ice climbing",
    "Ice racing",
    "Indoor skydiving",
    "Jet skiing",
    "Kitesurfing",
    "Motocross",
    "Mountain biking",
    "Parkour",
    "Parasailing",
    "Rock climbing",
    "Sandboarding",
    "Scuba diving",
    "Skydiving",
    "Snowboarding",
    "Snowmobiling",
    "Surfing",
    "Wakeboarding",
    "Windsurfing",
    "Ziplining",
    "Zorbing",
    "Air sports",
    "Amateur sports",
    "Animal sports",
    "Archery",
    "Auto racing",
    "Baseball",
    "Basketball",
    "Biathlon",
    "Bocce ball",
    "Bodybuilding",
    "Bowling",
    "Boxing",
    "Camping",
    "Canoeing",
    "Canopying",
    "Caving",
    "Cheerleading",
    "Climbing",
    "Cricket",
    "Croquet",
    "Cycling",
    "Darts",
    "Diving",
    "Dog sport",
    "Equestrianism",
    "Fencing",
    "Field hockey",
    "Fishing",
    "Footbag",
    "Football",
    "Golf",
    "Handball",
    "Hang gliding",
    "Hiking",
    "Hobby horsing",
    "Hunting",
    "Inline skating",
    "Jogging",
    "Kay"
]

jobs = [
    "Accountant",
    "Actor/Actress",
    "Aerospace Engineer",
    "Air Traffic Controller",
    "Animator",
    "Archaeologist",
    "Architect",
    "Art Director",
    "Astronomer",
    "Attorney/Lawyer",
    "Auditor",
    "Baker",
    "Banker",
    "Barber/Hairdresser",
    "Bartender",
    "Biologist",
    "Bookkeeper",
    "Botanist",
    "Bus Driver",
    "Carpenter",
    "Chef",
    "Chemist",
    "Civil Engineer",
    "Clergy",
    "Clinical Psychologist",
    "Computer Programmer",
    "Conservationist",
    "Construction Worker",
    "Content Creator",
    "Copywriter",
    "Counselor",
    "Curator",
    "Customer Service Representative",
    "Data Analyst",
    "Dentist",
    "Dermatologist",
    "Detective",
    "Dietitian/Nutritionist",
    "Director",
    "Doctor/Physician",
    "Economist",
    "Electrician",
    "Engineer",
    "Environmental Scientist",
    "Event Planner",
    "Farmer/Agricultural Worker",
    "Fashion Designer",
    "Financial Analyst",
    "Firefighter",
    "Fitness Instructor/Personal Trainer",
    "Flight Attendant",
    "Florist",
    "Forensic Scientist",
    "Game Developer",
    "Geologist",
    "Graphic Designer",
    "Historian",
    "Human Resources Manager",
    "Illustrator",
    "Information Technology (IT) Specialist",
    "Insurance Agent",
    "Interior Designer",
    "Interpreter/Translator",
    "Journalist",
    "Judge",
    "Librarian",
    "Machinist",
    "Marketing Manager",
    "Massage Therapist",
    "Mathematician",
    "Medical Assistant",
    "Meteorologist",
    "Microbiologist",
    "Midwife",
    "Military Officer/Soldier",
    "Musician",
    "Nurse",
    "Occupational Therapist",
    "Operations Manager",
    "Optometrist",
    "Paralegal",
    "Paramedic",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Politician",
    "Preschool Teacher",
    "Professor/Lecturer",
    "Project Manager",
    "Psychiatrist",
    "Public Relations (PR) Specialist",
    "Real Estate Agent",
    "Receptionist",
    "Research Scientist",
    "Retail Sales Associate",
    "Social Worker",
    "Software Developer",
    "Speech-Language Pathologist",
    "Statistician",
    "Surgeon",
    "Surveyor",
    "Teacher",
    "Technical Writer",
    "Tour Guide",
    "Truck Driver",
    "Veterinarian",
    "Waiter/Waitress",
    "Web Developer",
    "Wedding Planner",
    "Zoologist"
]

values = [
    "Honesty",
    "Loyalty",
    "Kindness",
    "Empathy",
    "Compassion",
    "Trustworthiness",
    "Reliability",
    "Generosity",
    "Sense of humor",
    "Intelligence",
    "Open-mindedness",
    "Respectfulness",
    "Patience",
    "Independence",
    "Confidence",
    "Ambition",
    "Creativity",
    "Adventurousness",
    "Optimism",
    "Supportiveness",
    "Thoughtfulness",
    "Integrity",
    "Emotional intelligence",
    "Communication skills",
    "Humility",
    "Forgiveness",
    "Resilience",
    "Adaptability",
    "Tolerance",
    "Fairness",
    "Perseverance",
    "Authenticity",
    "Curiosity",
    "Positivity",
    "Gratitude",
    "Flexibility",
    "Self-discipline",
    "Sensitivity",
    "Assertiveness",
    "Self-awareness",
    "Understanding",
    "Acceptance",
    "Diligence",
    "Selflessness",
    "Leadership",
    "Altruism",
    "Self-reliance",
    "Diplomacy",
    "Sociability",
    "Determination"
]